services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data

volumes:
  postgres_data:
    driver_opts:
      type: none
      device: /tmp/postgres
      o: bind
